### PR TITLE
Update godeltaprof

### PR DESCRIPTION
**Pull request by westy92**
Update godeltaprof to latest (0.1.8).

### CODE REVIEW

**Review by korniltsev — APPROVED** [review]

**Comment by korniltsev** [comment]
@westy92  Did you not sign the CLA or is @CLAassistant tripping?

**Comment by westy92** [comment]
@korniltsev I signed it 👍

**Comment by korniltsev** [comment]
Thanks

**Comment by korniltsev** [comment]
pushed a new tag https://github.com/grafana/pyroscope-go/releases/tag/v1.1.2

**Pull request merged**
